services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LANGCHAIN4J_GOOGLE_AI_GEMINI_API_KEY: AIzaSyAzvLhp2M8-V_OOzQeP2Pw5G0-dFVn1g0I
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./ui/app:/app/app
      - ./ui/components:/app/components
      - ./ui/tsconfig.json:/app/tsconfig.json
      - ./ui/postcss.config.js:/app/postcss.config.js
      - ./ui/tailwind.config.js:/app/tailwind.config.js
    command: ["npm", "run", "dev"]

  mcp-server:
    build: ./mcp
    depends_on:
      - postgres
    tty: true
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
