package com.crust.menu.domain

import jakarta.persistence.*
import java.math.BigDecimal
import java.time.LocalDate
import java.time.LocalDateTime
import java.util.UUID

/**
 * Stores demand predictions per menu item per hour.
 * Generated by the DemandForecastService using weighted moving averages
 * over the item_sales_hourly aggregate data.
 */
@Entity
@Table(name = "item_demand_forecast")
class ItemDemandForecast(
    @Id
    val id: UUID = UUID.randomUUID(),

    @Column(name = "menu_item_id", nullable = false)
    val menuItemId: UUID,

    @Column(name = "item_name", nullable = false)
    val itemName: String,

    @Column(name = "forecast_date", nullable = false)
    val forecastDate: LocalDate,

    @Column(name = "hour_of_day", nullable = false)
    val hourOfDay: Int,

    @Column(name = "day_of_week", nullable = false)
    val dayOfWeek: Int,

    @Column(name = "predicted_quantity", precision = 10, scale = 2, nullable = false)
    var predictedQuantity: BigDecimal = BigDecimal.ZERO,

    @Column(name = "predicted_revenue", precision = 12, scale = 2, nullable = false)
    var predictedRevenue: BigDecimal = BigDecimal.ZERO,

    @Column(name = "confidence", precision = 5, scale = 4, nullable = false)
    var confidence: BigDecimal = BigDecimal.ZERO,

    @Column(name = "model_version", nullable = false)
    val modelVersion: String,

    @Column(name = "generated_at", nullable = false)
    val generatedAt: LocalDateTime = LocalDateTime.now()
)
